Fix directory removal on Python 2
aliBuild fails with the following traceback on Ubuntu 18.04:

    Using cached build for golang
    Traceback (most recent call last):
      File "/usr/local/bin/aliBuild", line 132, in <module>
        doMain(args, parser)
      File "/usr/local/bin/aliBuild", line 82, in doMain
        printer, msg, code = doBuild(args, parser)
      File "/usr/local/lib/python2.7/dist-packages/alibuild_helpers/build.py", line 862, in doBuild
        shutil.rmtree(dirname(hashFile), True)
      File "/usr/lib/python2.7/shutil.py", line 270, in rmtree
        rmtree(fullname, ignore_errors, onerror)
      File "/usr/lib/python2.7/shutil.py", line 270, in rmtree
        rmtree(fullname, ignore_errors, onerror)
      File "/usr/lib/python2.7/shutil.py", line 270, in rmtree
        rmtree(fullname, ignore_errors, onerror)
      File "/usr/lib/python2.7/shutil.py", line 264, in rmtree
        fullname = os.path.join(path, name)
      File "/usr/lib/python2.7/posixpath.py", line 73, in join
        path += '/' + b
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
    ++ report_pr_errors --no-comments

This is because some packages create strangely-named test files:

    [root@alibuild04 sw]# find . -name $'*\xc3*'
    ./ubuntu1804_x86-64/golang/1.15.6-3/test/fixedbugs/issue27836.dir/Ämain.go
    ./ubuntu1804_x86-64/golang/1.15.6-3/test/fixedbugs/issue27836.dir/Äfoo.go
    ./ubuntu1804_x86-64/golang/1.15.6-2/test/fixedbugs/issue27836.dir/Ämain.go
    ./ubuntu1804_x86-64/golang/1.15.6-2/test/fixedbugs/issue27836.dir/Äfoo.go
    ./ubuntu1804_x86-64/golang/1.15.6-1/test/fixedbugs/issue27836.dir/Ämain.go
    ./ubuntu1804_x86-64/golang/1.15.6-1/test/fixedbugs/issue27836.dir/Äfoo.go
    ./SOURCES/boost/v1.74.0/v1.74.0/libs/wave/test/testwave/testfiles/utf8-test-ßµ™∃

This PR should fix that. This change also works under Python 3.