Include clone_speedup_options in git fetch
This change is not only performance related, it should also fix the
missing blob object errors. Fetching with --filter=tree:0 should always
be more resilient to missing objects upstream

```
sh-5.1$ git fetch -f https://github.com/alisw/alibuild-recipe-tools
+refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/*
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 2), reused 6 (delta 2), pack-reused 0
Unpacking objects: 100% (6/6), 806 bytes | 806.00 KiB/s, done.
fatal: missing blob object '6f314120ba0359d1f73ad7d1d4a7f171fb36e8ac'
error: https://github.com/alisw/alibuild-recipe-tools did not send all necessary objects
```